parapos/config/routes.rb
Rails.application.routes.draw do
  get 'packjobs/index'

  resources :packjobs
  resources :rigs

  root 'packjobs#index'
end

parapos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

parapos/app/models/packjob.rb
class Packjob < ApplicationRecord
  validates :packer, presence: true
  validates :rig, presence: true

  self.per_page = 25
end

parapos/app/models/rig.rb
class Rig < ApplicationRecord
  has_many :packjobs
  validates :rig_type_number, presence: true
  self.per_page = 25

end

parapos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

parapos/app/controllers/packjobs_controller.rb
class PackjobsController < ApplicationController
  def index
    @packjobs = Packjob.paginate(page: params[:page]).order('id DESC')
  end

  def show
    @packjob = Packjob.find(params[:id])
  end

  def new
    @packjob = Packjob.new
  end

  def edit
    @packjob = Packjob.find(params[:id])
  end

  def create
    @packjob = Packjob.new(packjob_params)

    if @packjob.save
      redirect_to @packjob
    else
      render 'new'
    end
  end


  def update
    @packjob = Packjob.find(params[:id])

    if @packjob.update(packjob_params)
      redirect_to @packjob
    else
      render 'edit'
    end
  end


  def destroy
    @packjob = Packjob.find(params[:id])
    @packjob.destroy

    redirect_to packjobs_path
  end

  private
    def packjob_params
      params.require(:packjob).permit(:packer, :rig)
    end

end

parapos/app/controllers/rigs_controller.rb
class RigsController < ApplicationController

  def index
    @rigs = Rig.paginate(page: params[:page]).order('id DESC')
  end

  def show
    @rig = Rig.find(params[:id])
  end

  def new
    @rig = Rig.new
  end

  def edit
    @rig = Rig.find(params[:id])
  end

  def create
    @rig = Rig.new(rig_params)

    if @rig.save
      redirect_to @rig
    else
      render 'new'
    end
  end


  def update
    @rig = Rig.find(params[:id])

    if @rig.update(rig_params)
      redirect_to @rig
    else
      render 'edit'
    end
  end


  def destroy
    @rig = Rig.find(params[:id])
    @rig.destroy

    redirect_to rigs_path
  end

  private
    def rig_params
      params.require(:rig).permit(:rig_type_number)
    end
end

parapos/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

parapos/app/helpers/application_helper.rb
module ApplicationHelper
end

parapos/app/helpers/packjobs_helper.rb
module PackjobsHelper
end

parapos/app/helpers/rigs_helper.rb
module RigsHelper

  def rig_status_display(args)
    args[:boolStatus] ||= ''
    return_value = ''
    if args[:boolStatus] == true then
      return_value = 'ONLINE'
    else
  	return_value = 'OFFLINE'
    end
    return return_value
  end

end

parapos/app/helpers/welcome_helper.rb
module WelcomeHelper
end

parapos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parapos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

parapos/app/views/packjobs/_form.html.erb
<%= form_with model: @packjob, local: true do |form| %>

  <% if @packjob.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@packjob.errors.count, "error") %> prohibited
        this packjob from being saved:
      </h2>
      <ul>
        <% @packjob.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label Time.now.strftime("%m/%d/%Y %I:%M:%S %P") %><br />
    <p>
      <%= form.label :packer %><br>
      <%= form.text_field :packer %>
    </p>

    <p>
      <%= form.label :rig %><br>
      <%= form.text_field :rig %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  </div>
  
<% end %>

parapos/app/views/packjobs/edit.html.erb
<h1>Edit packjob</h1>

<%= render 'form' %>

<%= link_to 'Back', packjobs_path %>

parapos/app/views/packjobs/index.html.erb
<h1>Listing Packjobs</h1>

<%= link_to 'New Packjob', new_packjob_path %> | <br>

<br>

<div class="digg_pagination">
  <%= will_paginate @packjobs, :container => false %>
</div>

<table id=listtable CELLPADDING="4" border="1">
  <tr class="headerBlue" >
    <th>Datestamp</th>
    <th>Packer</th>
    <th>Rig</th>
    <th colspan="3"></th>
  </tr>

  <% @packjobs.each do |packjob| %>
  <tr class="<%= cycle('rowA', 'rowB') %>">
        <td><%= link_to packjob.created_at.strftime("%m/%d/%Y %I:%M:%S %P"),packjob_path(packjob.id) %></td>
        <td><%= packjob.packer %></td>
        <td><%= packjob.rig %></td>
        <td><%= link_to 'Show', packjob_path(packjob) %></td>
        <td><%= link_to 'Edit', edit_packjob_path(packjob) %></td>
        <td><%= link_to 'Destroy', packjob_path(packjob),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    <% end %>
  </tr>
</table>
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @packjobs %>
  </div>
  <%= will_paginate @packjobs,  :container => false %>
</div>

<br><%= link_to 'New Packjob', new_packjob_path %> |

parapos/app/views/packjobs/new.html.erb
<h1>New Packjob</h1>

<%= render 'form' %>

<%= link_to 'Back', packjobs_path %>

parapos/app/views/packjobs/show.html.erb
<p>
   <b>Datestamp:</b>
  <%= @packjob.created_at.strftime("%m/%d/%Y %I:%M %P") %><br>
</p>
<p>
  <strong>Packer:</strong>
  <%= @packjob.packer %>
</p>

<p>
  <strong>Rig:</strong>
  <%= @packjob.rig %>
</p>

<%= link_to 'Edit', edit_packjob_path(@packjob) %> |
<%= link_to 'Back', packjobs_path %>

parapos/app/views/rigs/_form.html.erb
<%= form_with model: @rig, local: true do |form| %>

  <% if @rig.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rig.errors.count, "error") %> prohibited
        this rig from being saved:
      </h2>
      <ul>
        <% @rig.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= form.label :rig_online %>
      <%= form.check_box :rig_status %>
    </p>

    <p>
      <%= form.label :rig_type %><br>
      <%= form.text_field :rig_type_number %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  </div>

<% end %>

parapos/app/views/rigs/edit.html.erb
<h1>Edit rig</h1>

<%= render 'form' %>

<%= link_to 'Back', rigs_path %>

parapos/app/views/rigs/index.html.erb
<h1>Listing Rigs</h1>

<br>

<table id=listtable CELLPADDING=4  border="1">
  <tr>
    <th>Status</th>
    <th>Rig </th>
  <%
=begin %>
    <th NOWRAP># Jumps</th>
    <th>Reserve Repack</th>
    <th>Rigger</th>
    <th>Repack Due</th>
    <th>Last Main Pack</th>
    <th>Last Packer</th>
<%
=end %>
    <th></th>
    <th></th>
  </tr>

<% @rigs.each do |rig| %>
 <tr class="<%= cycle('rowA', 'rowB') %>">
    <%
	if (rig.rig_status == true )
		dcolor="TD BGCOLOR=#00ff00"
	else
		dcolor="TD BGCOLOR=red"
	end %>

	<td <%=dcolor%> >
		<%= rig_status_display :boolStatus => rig.rig_status %>
	</td>
    <td><%= rig.rig_type_number %></td>
<%
=begin %>
    <td><%= rig.rig_jumpnum %></td>
    <td><%= rig.rig_res_last %></td>
    <td><%= rig.rig_res_who %></td>
    <td><%= rig.rig_res_due %></td>
    <td><%= rig.rig_main_last %></td>
    <td><%= rig.rig_main_who %></td>
<%
=end %>
    <td><%= link_to 'Show', rig %></td>
    <td><%= link_to 'Edit', edit_rig_path(rig) %></td>
    <td><%= link_to 'Destroy', rig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<br><%= link_to 'New Rig', new_rig_path %> |

parapos/app/views/rigs/new.html.erb
<h1>New Rig</h1>

<%= render 'form' %>

<%= link_to 'Back', rigs_path %>

parapos/app/views/rigs/show.html.erb
<p>
  <strong>Rig Status:</strong>
  <%= @rig.rig_status %>
</p>

<p>
  <strong>Rig Type Num:</strong>
  <%= @rig.rig_type_number %>
</p>

<%= link_to 'Edit', edit_rig_path(@rig) %> |
<%= link_to 'Back', rigs_path %>